"""empty message

Revision ID: 0bf279ca0807
Revises: 69a4228d1825
Create Date: 2021-05-09 16:11:11.516365

"""

# revision identifiers, used by Alembic.
revision = '0bf279ca0807'
down_revision = '69a4228d1825'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'page_id')
    op.alter_column('requests', 'zone_id', existing_type=sa.Integer(), type_=sa.VARCHAR(length=256))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('page_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.alter_column('requests', 'zone_id', type_=sa.Integer(), existing_type=sa.VARCHAR(length=256))

    # ### end Alembic commands ###
