"""empty message

Revision ID: 3de754ae9a5
Revises: 9bd5a3ad4a
Create Date: 2021-04-01 10:00:54.263415

"""

# revision identifiers, used by Alembic.
revision = "3de754ae9a5"
down_revision = "9bd5a3ad4a"

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("requests", sa.Column("click_time", sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "click_time")
    ### end Alembic commands ###
