"""empty message

Revision ID: 4945ec6fdd13
Revises: e02d09c4660e
Create Date: 2021-04-04 05:22:59.066509

"""

# revision identifiers, used by Alembic.
revision = "4945ec6fdd13"
down_revision = "e02d09c4660e"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
