"""empty message

Revision ID: 69a4228d1825
Revises: 566ebe2c07ab
Create Date: 2021-05-09 14:02:34.349511

"""

# revision identifiers, used by Alembic.
revision = '69a4228d1825'
down_revision = '566ebe2c07ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('page_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'page_id')
    # ### end Alembic commands ###
