"""empty message

Revision ID: 83c9b64f22a7
Revises: e3fb96fce5d0
Create Date: 2021-04-15 06:18:15.936582

"""

# revision identifiers, used by Alembic.
revision = "83c9b64f22a7"
down_revision = "e3fb96fce5d0"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests", sa.Column("user_agent_inconsistency", sa.Boolean(), nullable=True)
    )
    op.drop_column("requests", "user_agent_consitency")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests",
        sa.Column(
            "user_agent_consitency", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("requests", "user_agent_inconsistency")
    # ### end Alembic commands ###
