"""empty message

Revision ID: 9bd5a3ad4a
Revises: None
Create Date: 2021-04-01 03:55:16.854367

"""

# revision identifiers, used by Alembic.
revision = "9bd5a3ad4a"
down_revision = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mouse_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_hash_id", sa.String(length=256), nullable=False),
        sa.Column("x_client", sa.Integer(), nullable=True),
        sa.Column("y_client", sa.Integer(), nullable=True),
        sa.Column("x_window", sa.Integer(), nullable=True),
        sa.Column("y_window", sa.Integer(), nullable=True),
        sa.Column("event", sa.String(length=20), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hash_id", sa.String(length=256), nullable=False),
        sa.Column("ip_address", sa.String(length=256), nullable=False),
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=4), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("referrer", sa.String(length=256), nullable=True),
        sa.Column("detected", sa.Boolean(), nullable=True),
        sa.Column("predicted", sa.Boolean(), nullable=True),
        sa.Column("fingerprint_uploaded", sa.Boolean(), nullable=True),
        sa.Column("user_agent_consitency", sa.Boolean(), nullable=True),
        sa.Column("data_center_ip_address", sa.String(length=256), nullable=True),
        sa.Column("exist_bot_attributes", sa.String(length=256), nullable=True),
        sa.Column("browner_inconsistency", sa.Boolean(), nullable=True),
        sa.Column("os_inconsistency", sa.Boolean(), nullable=True),
        sa.Column("language_inconsistency", sa.Boolean(), nullable=True),
        sa.Column("resolution_inconsistency", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("requests")
    op.drop_table("mouse_events")
    ### end Alembic commands ###
