"""empty message

Revision ID: a6b99c5d6ea5
Revises: 83c9b64f22a7
Create Date: 2021-04-15 12:33:58.035137

"""

# revision identifiers, used by Alembic.
revision = "a6b99c5d6ea5"
down_revision = "83c9b64f22a7"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests", sa.Column("tracking_code", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "tracking_code")
    # ### end Alembic commands ###
