"""empty message

Revision ID: dc39e93f6e34
Revises: a6b99c5d6ea5
Create Date: 2021-04-25 11:45:16.966774

"""

# revision identifiers, used by Alembic.
revision = 'dc39e93f6e34'
down_revision = 'a6b99c5d6ea5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad_referrer_pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=1052), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=True),
    sa.Column('hostmin', sa.String(length=64), nullable=True),
    sa.Column('hostmax', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_ranges')
    op.drop_table('bad_referrer_pattern')
    # ### end Alembic commands ###
