"""empty message

Revision ID: e02d09c4660e
Revises: 3de754ae9a5
Create Date: 2021-04-04 05:10:59.629830

"""

# revision identifiers, used by Alembic.
revision = "e02d09c4660e"
down_revision = "3de754ae9a5"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    predictenum = postgresql.ENUM("not_predicted", "bot", "not_bot", name="predictenum")
    predictenum.create(op.get_bind())
    op.add_column(
        "requests",
        sa.Column(
            "predetermined_predict_result",
            sa.Enum("not_predicted", "bot", "not_bot", name="predictenum"),
            nullable=True,
        ),
    )
    op.add_column(
        "requests",
        sa.Column(
            "predict_result",
            sa.Enum("not_predicted", "bot", "not_bot", name="predictenum"),
            nullable=True,
        ),
    )
    op.drop_column("requests", "predicted")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests",
        sa.Column("predicted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("requests", "predict_result")
    op.drop_column("requests", "predetermined_predict_result")
    # ### end Alembic commands ###
