"""empty message

Revision ID: e3fb96fce5d0
Revises: 63b3be668a62
Create Date: 2021-04-15 06:17:23.546337

"""

# revision identifiers, used by Alembic.
revision = "e3fb96fce5d0"
down_revision = "63b3be668a62"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "size")
    op.drop_column("requests", "method")
    op.drop_column("requests", "referrer")
    op.drop_column("requests", "status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests",
        sa.Column("status", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "requests",
        sa.Column(
            "referrer", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "requests",
        sa.Column("method", sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    )
    op.add_column(
        "requests", sa.Column("size", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
