"""empty message

Revision ID: f3190e708dec
Revises: cd45f661e649
Create Date: 2021-04-25 12:08:45.753336

"""

# revision identifiers, used by Alembic.
revision = 'f3190e708dec'
down_revision = 'cd45f661e649'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('bad_referer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'bad_referer')
    # ### end Alembic commands ###
